INSERT INTO PRODUTOS (ID, NOME, VALOR, DESCRICAO) VALUES (1, 'Playstation 5', 4500, 'Console Video-Game');
INSERT INTO PRODUTOS (ID, NOME, VALOR, DESCRICAO) VALUES (2, 'Televisão 55'' 4K', 3000, 'Televisão');
INSERT INTO PRODUTOS (ID, NOME, VALOR, DESCRICAO) VALUES (3, 'Xbox Series S', 2400, 'Console Xbox');
