INSERT INTO PRODUTOS (NOME, VALOR, DESCRICAO) VALUES ('Playstation 5', 4500, 'Console Video-Game');
INSERT INTO PRODUTOS (NOME, VALOR, DESCRICAO) VALUES ('Televisão 55'' 4K', 3000, 'Televisão');
INSERT INTO PRODUTOS (NOME, VALOR, DESCRICAO) VALUES ('Xbox Series S', 2400, 'Console Xbox');
INSERT INTO PRODUTOS (NOME, VALOR, DESCRICAO) VALUES ('Processador I5-10400', 1529.29, 'Hardware');
INSERT INTO PRODUTOS (NOME, VALOR, DESCRICAO) VALUES ('Iphone 13', 6000, 'Celular');
INSERT INTO PRODUTOS (NOME, VALOR, DESCRICAO) VALUES ('Cadeira', 2400, 'Gamer');
INSERT INTO PRODUTOS (NOME, VALOR, DESCRICAO) VALUES ('Cooler FAN Rise Mode', 17.53, 'Computador');
