spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  application:
    name: store
    profile:
      active: dev
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 0
  liquibase:
    contexts: default
    changeLog: classpath:db/db-master.xml

server:
  port: 8081